### ISSUE TITLE
echo failed, sent %x__ yet got %x__

### ISSUE THREAD

**Issue by objt-ba** [spook/sshping#20]
I keep getting messages like:

    *** Echo failed, sent %x43 yet got %x1b

and

    *** Echo failed, sent %x62 yet got %x1b

Nevertheless, the device is reachable. 

Could you give me some more background about the meaning of this error ?
Does it mean that my server is too slow ?

**Comment by spook** [comment]
Hello @objt-ba, it means that what it sent is not what it got back.  For the echo test, it sends one character at a time and waits to see what it gets back.  It expects to see the same character returned.  The %x codes are the hexadecimal values of the characters it sent and what it saw in return.  For example, %x43 is the uppercase letter 'C', %x62 is the lowercase letter 'b', and %x1b is the escape character.  

When `sshping` logs into the remote system, it expects a Linux-like shell and gives it the ``--echocmd`` command so that whatever it sends next, will be echo'd back.  By default this command is `cat > /dev/null` which would normally show the character echo of whatever was typed.  If your remote server does not understand that command, then use the `--echocmd` option to change it to something that causes each character to be echo'd correctly.

I hope this helps,
-- Uncle Spook

**Comment by Rayqan** [comment]
Had the same issue seemed to be zsh (switched default shell to sh).

**Comment by Madoshakalaka** [comment]
I was using zsh and had the same problem. Switched to sh and it worked.
